# Generated by Django 5.2 on 2026-10-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Подпись')),
                ('category', models.CharField(choices=[('nature', 'Природа'), ('yurts', 'Юрты'), ('rooms', 'Номера'), ('kymyz', 'Кымыз'), ('rest', 'Отдых')], default='nature', max_length=20, verbose_name='Категория')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('badge', models.CharField(blank=True, help_text='Например: −20%', max_length=40, verbose_name='Метка')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Город')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка')),
                ('source', models.CharField(default='Сайт', max_length=40, verbose_name='Источник')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('cottage', 'Номер в коттедже'), ('yurt', 'Юрта')], default='cottage', max_length=20, verbose_name='Тип')),
                ('short_description', models.CharField(max_length=255, verbose_name='Кратко')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость, чел.')),
                ('beds', models.CharField(max_length=120, verbose_name='Кровати')),
                ('amenities', models.TextField(help_text='Каждое удобство с новой строки', verbose_name='Удобства')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера и юрты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Якорь')),
                ('icon', models.CharField(default='leaf', help_text='Имя иконки из спрайта: leaf, spa, horse, bath, car, yurt, fire, cup', max_length=40, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Услуги и прайс',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номера',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveSmallIntegerField(verbose_name='Гостей')),
                ('price_full', models.PositiveIntegerField(help_text='Проживание + трёхразовое питание + пятиразовое кобылье молоко', verbose_name='Цена с питанием и кымызом, сом/сутки')),
                ('price_room_only', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена без питания и молока, сом/сутки')),
                ('note', models.CharField(blank=True, help_text='Например: «с человека 3150 сом» или «доп. место 2480 сом»', max_length=120, verbose_name='Примечание')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-guests'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Наименование')),
                ('duration', models.CharField(blank=True, max_length=60, verbose_name='Время / объём')),
                ('price', models.CharField(help_text='Например: 2000 сом/час', max_length=60, verbose_name='Цена')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='Примечание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
                'ordering': ['order', 'id'],
            },
        ),
    ]
