# Generated by Django 5.2 on 2026-10-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/', verbose_name='Изображение')),
                ('static_image', models.CharField(blank=True, help_text='Путь внутри static/, например img/room-lux.jpg. Используется, только если не загружено изображение.', max_length=255, verbose_name='Картинка из static')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Надзаголовок')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Кымызолечебница «Байтур»', max_length=120, verbose_name='Название')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('phone', models.CharField(help_text='В формате +996 770 797 370', max_length=40, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=40, verbose_name='Доп. телефон')),
                ('whatsapp', models.CharField(help_text='Например 996770797370', max_length=20, verbose_name='WhatsApp (только цифры)')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='Ссылка WhatsApp')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_note', models.CharField(blank=True, max_length=255, verbose_name='Как добраться (кратко)')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту (2GIS)')),
                ('map_embed', models.URLField(blank=True, verbose_name='Встраиваемая карта (iframe src)')),
                ('season', models.CharField(blank=True, max_length=120, verbose_name='Сезон')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
